version: '3'
services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./app:/code
            - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
        logging:
            options:
                max-size: "100m"
                max-file: "10"
    php:
        build: ./php
        volumes:
            - ./app:/code
        logging:
            options:
                max-size: "100m"
                max-file: "10"
